### PR TITLE
Implement OAuth authorization code grant

### PR DESCRIPTION
**Pull request by alexsegura**
This will display an authorization page so that the user can grant access to the OAuth client. 

Example OAuth URL:

```
http://localhost/oauth2/authorize?response_type=code&client_id=ClientId&redirect_uri=http://localhost/cb&scope=*
```

Once the user has approved the request, he/she will we redirected to the `redirect_uri` with a `code` parameter that allows to retrieve an access token. 

Example cURL request to retrieve an access token:

```
 curl -v -X POST -d 'grant_type=authorization_code&client_secret=ClientSecret&client_id=ClientId&redirect_uri=http://localhost/cb&code=<INSERT_AUTH_CODE_HERE>' http://localhost/oauth2/token
```

Capture d’écran 2022-06-10 à 09 47 46

### CODE REVIEW

**Comment by alexsegura** [comment]
@janssens this is a first step. The next step is to make the OAuth flow more "smart":
- by allowing the user to register (right now the `/oauth2/authorize` route expects the user to be authenticated) 
- by allowing the user to credit the wallet if needed

**Comment by janssens** [comment]
When in visit
`http://localhost/oauth2/authorize?response_type=code&client_id=<ID>&redirect_uri=http://localhost/cb&scope=*`

I got 
{"error":"invalid_client","error_description":"Client authentication failed","message":"Client authentication failed"}

Without redirect_uri it's ok :
`http://localhost/oauth2/authorize?response_type=code&client_id=<ID>`

what should we set for "redirect url" in the client table ?

I also miss the deny button
image
Maybe my assets are not up to date ?

For the layout, I let you know there is a dedicated layout for in_app action, without header and footer. I don't know if its better or not ?
see **templates/in_app.html.twig** user in **templates/order/pay.html.twig**

**Comment by alexsegura** [comment]
> what should we set for "redirect url" in the client table ?

You can set any `redirect_uri` in the client table, but just make sure to specify the same one when calling the authorize endpoint.

**Comment by alexsegura** [comment]
> I also miss the deny button

Strange, I'm using the `bg-pink-600` and `hover:bg-pink-900` colors, aren't they standard colors?

**Comment by janssens** [comment]
> aren't they standard colors?

Yes they are, https://v2.tailwindcss.com/docs/background-color  
There is a css purge in production, but not in dev, it should work.

**Comment by janssens** [comment]
It's ok, the _npm run dev_ command solve the issue.

**Comment by alexsegura** [comment]
Great! Is anything else blocking the merge?

**Pull request merged**
